### PR TITLE
Contributed to #22. Added Norwegian translation

### PR DESCRIPTION
**Pull request by Ondkloss**
Added Norwegian translation based of a freshly built base.pot.
Contains both the .po and .mo. Added under 0.0.2.

### CODE REVIEW

**Comment by arvchristos** [comment]
Thanks a lot! This pot refers to the UI elements of the add-on. If you wish to contribute more elements, I suggest you use the l10n utility to localize help pages as well as the extension description and additional metadata

**Comment by arvchristos** [comment]
@Ondkloss please check #24 if interested

**Comment by Ondkloss** [comment]
@arvchristos I'll take a look at it and see what I can do. As a quick note I think that all are doable by me except the license. Either it already exists with an official Norwegian translation, or someone with a law background would have to do it. I dare not attempt any license translation by myself. I'll see if I can contribute towards the rest tomorrow.

**Comment by arvchristos** [comment]
@Ondkloss Thank you ! The licence should be found translated (all gpl ones are widely used)

**Comment by arvchristos** [comment]
@Ondkloss Your contribution will be part of the next minor release(0_0_3). Thank you for the contribution!

**Pull request merged**
