### PR TITLE
Wiki

### PR DESCRIPTION
**Pull request by io-ma**

### CODE REVIEW

**Comment by arvchristos** [comment]
@io-ma I have already included wiki pages in this repository wiki. Could you explain what is changed here?

**Comment by io-ma** [comment]
I reviewed all the pages and I found some things that needed correction.(like a few mis-types, a few phrases that needed reordering because they were too long etc. I fixed everything.
Will need to solve the conflicts first.

**Comment by arvchristos** [comment]
Oh that's fine, I will review the changes and include them as soon as possible !
Thank you

**Comment by io-ma** [comment]
wait a sec, I have a conflicting file, will solve it now

**Comment by io-ma** [comment]
Thing is I created a local dir called StyleWiki so you can't merge with mine, but here it is:
https://github.com/io-ma/lo-page-numbering/tree/master/StyleWiki

**Comment by arvchristos** [comment]
> Thing is I created a local dir called StyleWiki so you can't merge with mine, but here it is:
> https://github.com/io-ma/lo-page-numbering/tree/master/StyleWiki

Would you submit a pull request for me to include those changes?

**Comment by io-ma** [comment]
It shows me there are conflicts and I can not solve them from gitthub, that button is greyed out, so the easiest way is you copy the pages then I nuke this dir and do fetch/merge.
Ok, I created a separate repo: https://github.com/io-ma/StyleWiki

**Pull request closed without merging**
