### PR TITLE
PEP8 for main.py

### PR DESCRIPTION
**Pull request by ghost**
In-progress. Do not merge it.

### CODE REVIEW

**Comment by ghost** [comment]
I used a little bit autopep8, then I read the code again. Can you have a look? @arvchristos

**Comment by arvchristos** [comment]
> I used a little bit autopep8, then I read the code again. Can you have a look? @arvchristos

@midnio 
I tested just in case anything is broken and everything seems to be fine. Do you intend to change anything or should I merge your changes?

**Comment by arvchristos** [comment]
@midnio  I figured you completed the formatting. Thank you for the time!

**Comment by ghost** [comment]
No problem :P

**Pull request merged**
